=== CLKL/lab10/Schedule.dtd
<!ELEMENT schedule (days| periods|courses)+>

<!ELEMENT booking (((day, period)|(period, course)|(day, course)), room, instructor)>

<!-- Course Perspective -->
<!ELEMENT courses (course)+>
<!ELEMENT course (booking|EMPTY)*>
<!ATTLIST course course_num (4650|4910|4660|4770|4850|4620) #REQUIRED>

<!-- Period Perspective -->
<!ELEMENT periods (period)+>
<!ELEMENT period (booking|EMPTY)*>
<!ATTLIST period
	time (830|930|1030|1130|1230|1330|1430|1530|1630)
	#REQUIRED >

<!-- Day Perspective -->
<!ELEMENT days(day)+>
<!ELEMENT day (booking|EMPTY)*>
<!ATTLIST day num (1|2|3|4|5) #REQUIRED>

<!-- ELEMENTS -->
		
<!ELEMENT room (#PCDATA)>

<!ELEMENT instructor (#PCDATA)>

=== CLKL/lab10/dayOfWeek.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE days SYSTEM "Schedule.dtd">

<!--
    Document   : dayOfWeek.xml
    Created on : March 07, 2016, 9:00 PM
    Author     : Kelly Liu
-->
<days>
    <day num="4">
        <booking>
		<period time="930"></period>
        <course course_num="4910"></course>
        <room>SW5-1850</room>	
        <instructor>Richard Chau</instructor>
		</booking>
		<booking>
        <period time="1030"></period>
        <course course_num="4910"></course>
        <room>SE12-306</room>
        <instructor>Richard Chau</instructor>
		</booking>
		<booking>
        <period time="1130"></period>
        <course course_num="4910"></course>
        <room>SE12-306</room>
        <instructor>Richard Chau</instructor>
		</booking>
		<booking>
        <period time="1330"></period>
        <course course_num="4850"></course>
        <room>SE12-308</room>
        <instructor>James Parry</instructor>
        </booking>
		<booking>
        <period time="1430"></period>
        <course course_num="4850"></course>
        <room>SE12-308</room>
        <instructor>James Parry</instructor>
		</booking>
    </day>
</days>

=== CLKL/lab10/course.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courses SYSTEM "Schedule.dtd">

<courses>
    <course course_num="4650">
    <booking>
		<day num="1">Monday</days>
		<period time="1030"></period>
		<room>SE12 306</room>
		<instructor>Medhat Elmasry</instructor>
	</booking>
	<booking>
		<day num="1">Monday</days>
		<period time="1130"></period>
		<room>SE12 306</room>
		<instructor>Medhat Elmasry</instructor>
	</booking>
	<booking>
		<day num="1">Monday</days>
		<period time="1630"></period>
		<room>SE6 205</room>
		<instructor>Medhat Elmasry</instructor>
	</booking>
    </course>
</courses>

=== CLKL/lab10/period.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE periods SYSTEM "Schedule.dtd">

<periods>
    <period time="1130">
		<booking>
        <course course_nunm="4650"></course>
        <day num="1"></dayOfWeek>
        <room>SE12-306</room>
        <instructor>Dargahi, Farnaz</instructor>
        </booking>
		<booking>
	<course course_num="4910"></course>
        <day num="4"></dayOfWeek>
        <room>SE12-306</room>
        <instructor>Richard Chau</instructor>
        </booking>
		<booking>
        <course course_num="4770"></course>       
        <day num="5"></dayOfWeek>
        <room>SE12-306</room>
        <instructor>Trevor Lord</instructor>
        </booking>
    </period>
</periods>
